
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANCHOREND ANCHORSTART BOXOFFICE CAST CASTEND COMMA CONTENT DIRECTORS DIVEND LANGUAGE MOVIETITLE PRODUCERS ROLE RUNTIME STORY WRITERS\n    ss : director\n            | writer\n            | producer\n            | language\n            | cast\n            | story\n            | boxoffice\n            | runtime\n            | movietitle\n            | empty            \n    \n    movietitle : MOVIETITLE CONTENT    \n    \n    director :  DIRECTORS CONTENT         \n    \n    writer : WRITERS f DIVEND\n    \n    f : f COMMA ANCHORSTART CONTENT ANCHOREND\n    \n    f : ANCHORSTART CONTENT ANCHOREND\n    \n    producer : PRODUCERS g DIVEND\n    \n    g : g COMMA ANCHORSTART CONTENT ANCHOREND\n    \n    g : ANCHORSTART CONTENT ANCHOREND\n    \n    language : LANGUAGE CONTENT\n    \n    cast : CAST CONTENT ROLE CONTENT CASTEND\n    \n    story : STORY CONTENT\n    \n    boxoffice : BOXOFFICE CONTENT\n    \n    runtime : RUNTIME CONTENT\n    \n    empty : \n    '
    
_lr_action_items = {'DIRECTORS':([0,],[12,]),'WRITERS':([0,],[13,]),'PRODUCERS':([0,],[14,]),'LANGUAGE':([0,],[15,]),'CAST':([0,],[16,]),'STORY':([0,],[17,]),'BOXOFFICE':([0,],[18,]),'RUNTIME':([0,],[19,]),'MOVIETITLE':([0,],[20,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,21,26,28,29,30,31,32,35,46,],[-24,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-12,-19,-21,-22,-23,-11,-13,-16,-20,]),'CONTENT':([12,15,16,17,18,19,20,23,25,38,39,41,],[21,26,27,28,29,30,31,34,37,43,44,45,]),'ANCHORSTART':([13,14,33,36,],[23,25,39,41,]),'DIVEND':([22,24,40,42,47,48,],[32,35,-15,-18,-14,-17,]),'COMMA':([22,24,40,42,47,48,],[33,36,-15,-18,-14,-17,]),'ROLE':([27,],[38,]),'ANCHOREND':([34,37,44,45,],[40,42,47,48,]),'CASTEND':([43,],[46,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ss':([0,],[1,]),'director':([0,],[2,]),'writer':([0,],[3,]),'producer':([0,],[4,]),'language':([0,],[5,]),'cast':([0,],[6,]),'story':([0,],[7,]),'boxoffice':([0,],[8,]),'runtime':([0,],[9,]),'movietitle':([0,],[10,]),'empty':([0,],[11,]),'f':([13,],[22,]),'g':([14,],[24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ss","S'",1,None,None,None),
  ('ss -> director','ss',1,'p_ss','LexerParser.py',123),
  ('ss -> writer','ss',1,'p_ss','LexerParser.py',124),
  ('ss -> producer','ss',1,'p_ss','LexerParser.py',125),
  ('ss -> language','ss',1,'p_ss','LexerParser.py',126),
  ('ss -> cast','ss',1,'p_ss','LexerParser.py',127),
  ('ss -> story','ss',1,'p_ss','LexerParser.py',128),
  ('ss -> boxoffice','ss',1,'p_ss','LexerParser.py',129),
  ('ss -> runtime','ss',1,'p_ss','LexerParser.py',130),
  ('ss -> movietitle','ss',1,'p_ss','LexerParser.py',131),
  ('ss -> empty','ss',1,'p_ss','LexerParser.py',132),
  ('movietitle -> MOVIETITLE CONTENT','movietitle',2,'p_movietitle','LexerParser.py',140),
  ('director -> DIRECTORS CONTENT','director',2,'p_director','LexerParser.py',148),
  ('writer -> WRITERS f DIVEND','writer',3,'p_writer','LexerParser.py',157),
  ('f -> f COMMA ANCHORSTART CONTENT ANCHOREND','f',5,'p_f_recurse','LexerParser.py',166),
  ('f -> ANCHORSTART CONTENT ANCHOREND','f',3,'p_f_term','LexerParser.py',180),
  ('producer -> PRODUCERS g DIVEND','producer',3,'p_producer','LexerParser.py',194),
  ('g -> g COMMA ANCHORSTART CONTENT ANCHOREND','g',5,'p_g_recurse','LexerParser.py',203),
  ('g -> ANCHORSTART CONTENT ANCHOREND','g',3,'p_g_term','LexerParser.py',217),
  ('language -> LANGUAGE CONTENT','language',2,'p_language','LexerParser.py',231),
  ('cast -> CAST CONTENT ROLE CONTENT CASTEND','cast',5,'p_cast','LexerParser.py',240),
  ('story -> STORY CONTENT','story',2,'p_story','LexerParser.py',251),
  ('boxoffice -> BOXOFFICE CONTENT','boxoffice',2,'p_boxoffice','LexerParser.py',260),
  ('runtime -> RUNTIME CONTENT','runtime',2,'p_runtime','LexerParser.py',269),
  ('empty -> <empty>','empty',0,'p_empty','LexerParser.py',278),
]
